<LeaderboardScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Leaderboard'
            font_size: '25sp'
        Leaderboard:
            size_hint: 1, 2.5
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            Button:
                text: 'Menu'
                font_size: '30sp'
                on_press: root.manager.current = 'menu'
                size_hint: 1, .75