<ReviewScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Review'
            font_size: '25sp'
        ReviewGrid:
            cols: 4
            size_hint: 1, 1.75
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            Button:
                text: 'Menu'
                font_size: '30sp'
                on_press: root.manager.current = 'menu'
                size_hint: 1, .5